/**
 * Managed-file identity - the ONE source of truth for the `marver:managed <hash>` marker,
 * shared by `init` (which WRITES managed files) and `dev`'s boot-time staleness probe (which
 * only READS them). Kept side-effect-free on purpose: dev must learn whether the on-disk
 * instructions are behind the installed package WITHOUT importing the mutating init() path.
 */
import { createHash } from 'node:crypto'
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

/** The marker records a HASH of the generated body: edits are DETECTED, not assumed. */
export const MANAGED_PREFIX = '<!-- marver:managed '
/** Hashless 0.2.2-dev marker: edits are undetectable, so init unconditionally upgrades it. */
export const LEGACY_PREFIX = '<!-- generated by marver init'
export const hashBody = (s: string) => createHash('sha256').update(s).digest('hex')

/** Prepend the managed marker to a generated body. Deleting the marker line detaches the
 *  file from updates entirely. */
export const managedFile = (body: string) =>
  `${MANAGED_PREFIX}${hashBody(body)} - edit freely: init preserves your edits and stages upstream updates at design/.local/latest/ for you to merge. Delete this line to detach this file from updates entirely. -->\n${body}`

/** Package root = the nearest ancestor holding templates/ (one hop from dist/, two from
 *  src/** - the walk serves both, and tests run from source). */
export const pkgDir = (): string => {
  let dir = dirname(fileURLToPath(import.meta.url))
  for (let i = 0; i < 4; i++) {
    if (existsSync(join(dir, 'templates'))) return dir
    dir = dirname(dir)
  }
  return join(dirname(fileURLToPath(import.meta.url)), '..')
}
export const templatesDir = (): string => join(pkgDir(), 'templates')

/** Three-way marker state, split so the probe can tell an upgrade-behind file (report) from a
 *  user-owned one (never nag). Mirrors init's writeManaged classification EXACTLY:
 *  pristine = body still hashes to the recorded base; the base is `current` when it equals the
 *  freshly-shipped body's hash, else `stale` (the package moved on). Edited files split the
 *  same way on their recorded base. */
export type ManagedState =
  | 'absent'            // file missing entirely
  | 'pristine-current'  // unedited, matches the shipped version
  | 'pristine-stale'    // unedited, but the package shipped a newer body
  | 'edited-current'    // user-edited, forked from the current base (init stays silent)
  | 'edited-stale'      // user-edited, forked from an OLD base (init stages + warns)
  | 'legacy'            // hashless old marker (init upgrades unconditionally)
  | 'detached'          // marker removed = documented opt-out; never touched

export function classifyManaged(current: string | null, shippedBody: string): ManagedState {
  if (current == null) return 'absent'
  if (current.startsWith(MANAGED_PREFIX)) {
    const nl = current.indexOf('\n')
    if (nl < 0) return 'detached'                                   // malformed one-liner: leave it be
    const recorded = current.slice(MANAGED_PREFIX.length).split(' ')[0]
    if (!/^[0-9a-f]{64}$/.test(recorded)) return 'detached'          // not a real sha256: a mangled marker, leave it be
    const body = current.slice(nl + 1)
    const shipped = hashBody(shippedBody)
    if (hashBody(body) === recorded) return recorded === shipped ? 'pristine-current' : 'pristine-stale'
    return recorded === shipped ? 'edited-current' : 'edited-stale'
  }
  if (current.startsWith(LEGACY_PREFIX)) return 'legacy'
  return 'detached'
}

/** The managed INSTRUCTION set init writes, enumerated identically (init.ts): top-level
 *  templates/instructions/*.md plus one level of subdirectory *.md (reference/). setup.md is
 *  the SETUP_MD constant written separately/conditionally - it is not a template file, so it
 *  never appears here. */
export function enumerateInstructionTemplates(templatesRoot: string): { rel: string; body: string }[] {
  const instrRoot = join(templatesRoot, 'instructions')
  const out: { rel: string; body: string }[] = []
  if (!existsSync(instrRoot)) return out
  for (const e of readdirSync(instrRoot, { withFileTypes: true })) {
    if (e.isDirectory()) {
      for (const f of readdirSync(join(instrRoot, e.name)))
        if (f.endsWith('.md')) out.push({ rel: `instructions/${e.name}/${f}`, body: readFileSync(join(instrRoot, e.name, f), 'utf8') })
    } else if (e.name.endsWith('.md') && e.name !== 'setup.md') {   // setup.md is the SETUP_MD constant, written separately/conditionally
      out.push({ rel: `instructions/${e.name}`, body: readFileSync(join(instrRoot, e.name), 'utf8') })
    }
  }
  return out
}

const STALE: ReadonlySet<ManagedState> = new Set(['absent', 'pristine-stale', 'edited-stale', 'legacy'])

/**
 * Which managed instruction files on disk are behind the INSTALLED package (distinct from the
 * registry update-check). Returns display names (basenames) of the stale files, AGENTS.md
 * included only when the file is entirely ABSENT (a deleted marker is the documented opt-out,
 * and AGENTS.md is host-substituted so its pristine hash never matches the raw template).
 * Never throws: any read/enumeration failure yields an empty list so a boot can't crash on it.
 */
export function staleManagedInstructions(root: string): string[] {
  try {
    const design = join(root, 'design')
    const stale: string[] = []
    for (const { rel, body } of enumerateInstructionTemplates(templatesDir())) {
      const file = join(design, rel)
      const current = existsSync(file) ? readFileSync(file, 'utf8') : null
      if (STALE.has(classifyManaged(current, body))) stale.push(rel.split('/').pop() ?? rel)
    }
    // AGENTS.md: substituted at init, so hash-compare is meaningless - only a wholly missing
    // contract is a reliable, actionable signal (re-init restores it).
    if (!existsSync(join(design, 'AGENTS.md'))) stale.unshift('AGENTS.md')
    return stale
  } catch {
    return []
  }
}
