import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { init } from '../src/cli/init.ts'

/** init tests run against a real temp dir - init is filesystem-in, filesystem-out. */
let root: string
beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), 'mv-init-'))
  writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'host', devDependencies: {} }))
  vi.spyOn(console, 'log').mockImplementation(() => {})
  vi.spyOn(console, 'warn').mockImplementation(() => {})
  vi.spyOn(console, 'error').mockImplementation(() => {})
})
afterEach(() => {
  rmSync(root, { recursive: true, force: true })
  vi.restoreAllMocks()
})

const OPTS = { mode: 'studio' as const, demo: false }
const read = (rel: string) => readFileSync(join(root, 'design', rel), 'utf8')

describe('init: the method layer (0.2.2)', () => {
  it('scaffolds instructions/ with hashed markers, and setup.md in a no-app repo', () => {
    init(root, OPTS)
    for (const f of ['configure', 'discover', 'wireframe', 'brand', 'craft', 'components', 'review', 'boards'])
      expect(read(`instructions/${f}.md`)).toMatch(/^<!-- marver:managed [0-9a-f]{64} /)
    for (const f of ['layout', 'typography', 'color', 'motion', 'copy', 'tune', 'critique', 'states', 'delight', 'operate', 'concepts', 'slop'])
      expect(read(`instructions/reference/${f}.md`)).toMatch(/^<!-- marver:managed [0-9a-f]{64} /)
    expect(read('instructions/setup.md')).toContain('# Setup required')
    expect(read('AGENTS.md')).toContain('design/instructions/setup.md')
    expect(read('AGENTS.md')).toContain('## The method (binding)')
  })

  it('re-init after the app appears: deletes setup.md, regenerates the contract', () => {
    init(root, OPTS)
    writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'host', devDependencies: { tailwindcss: '^4.0.0' } }))
    mkdirSync(join(root, 'src'), { recursive: true })
    writeFileSync(join(root, 'src', 'index.css'), '@import "tailwindcss";')
    init(root, OPTS)
    expect(existsSync(join(root, 'design', 'instructions', 'setup.md'))).toBe(false)
    expect(read('AGENTS.md')).not.toContain('STOP - this repo has no app yet')
    expect(read('AGENTS.md')).toContain("app's Tailwind classes")
  })

  it('managed lifecycle: pristine updates, edits are preserved + staged, detached is untouched', () => {
    const h = (s: string) => createHash('sha256').update(s).digest('hex')
    init(root, OPTS)
    const craft = join(root, 'design', 'instructions', 'craft.md')
    const latest = join(root, 'design', '.local', 'latest', 'instructions', 'craft.md')

    // PRISTINE with an outdated body (hash matches its own body, differs from template) -> updated
    writeFileSync(craft, `<!-- marver:managed ${h('stale\n')} -->\nstale\n`)
    init(root, OPTS)
    expect(read('instructions/craft.md')).toContain('# Craft')

    // EDITED and upstream moved (recorded hash matches neither body nor template) ->
    // body preserved verbatim, fresh version staged, marker bumped to the new base
    // so the note fires once per release
    writeFileSync(craft, `<!-- marver:managed ${h('some old base\n')} -->\n# Craft, but MY version\n`)
    init(root, OPTS)
    expect(read('instructions/craft.md')).toContain('# Craft, but MY version')
    expect(readFileSync(latest, 'utf8')).toContain('# Craft')
    const bumpedHash = read('instructions/craft.md').slice('<!-- marver:managed '.length).split(' ')[0]
    const templateBody = readFileSync(latest, 'utf8')
    expect(bumpedHash).toBe(h(templateBody))
    // ...and the next init is silent for this file (base is now current)
    const warns: string[] = []
    ;(console.warn as any).mockImplementation((m: string) => warns.push(m))
    init(root, OPTS)
    expect(warns.filter((w) => w.includes('instructions/craft.md'))).toEqual([])

    // EDITED but upstream unchanged since their base (recorded hash == template hash)
    // -> preserved, silent, nothing staged
    rmSync(latest)
    const template = read('instructions/discover.md')
    const recorded = template.slice('<!-- marver:managed '.length).split(' ')[0]
    writeFileSync(join(root, 'design', 'instructions', 'discover.md'),
      `<!-- marver:managed ${recorded} -->\nmy tuned discover\n`)
    init(root, OPTS)
    expect(read('instructions/discover.md')).toContain('my tuned discover')
    expect(existsSync(join(root, 'design', '.local', 'latest', 'instructions', 'discover.md'))).toBe(false)

    // DETACHED: marker deleted -> never touched
    writeFileSync(craft, '# my own rules\n')
    init(root, OPTS)
    expect(read('instructions/craft.md')).toBe('# my own rules\n')

    // LEGACY hashless marker (0.2.2-dev era) -> upgraded onto hashed markers
    writeFileSync(craft, '<!-- generated by marver init (older wording) -->\nstale\n')
    init(root, OPTS)
    expect(read('instructions/craft.md')).toMatch(/^<!-- marver:managed [0-9a-f]{64} /)

    // MALFORMED one-line marker file (no newline, no body): bytes must survive
    const weird = '<!-- marver:managed junk with user words and no newline'
    writeFileSync(craft, weird)
    init(root, OPTS)
    expect(read('instructions/craft.md')).toBe(weird)
  })

  it('collision guard: refuses a non-marver design/, allows a marver-shaped one', () => {
    mkdirSync(join(root, 'design'))
    writeFileSync(join(root, 'design', 'assets.txt'), 'not ours')
    const exit = vi.spyOn(process, 'exit').mockImplementation(() => { throw new Error('exit') })
    expect(() => init(root, OPTS)).toThrow('exit')
    expect(exit).toHaveBeenCalledWith(1)
    // marver-shaped by content: config.ts mentioning marver
    writeFileSync(join(root, 'design', 'config.ts'), '// marver config\nexport default {}\n')
    expect(() => init(root, OPTS)).not.toThrow()
  })

  it('a foreign setup.md is never deleted', () => {
    init(root, OPTS)   // no-app: writes our setup.md
    const setup = join(root, 'design', 'instructions', 'setup.md')
    writeFileSync(setup, 'my personal setup notes\n')
    writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'host', devDependencies: { tailwindcss: '^4.0.0' } }))
    init(root, OPTS)   // app detected - would delete OUR setup.md, must keep theirs
    expect(read('instructions/setup.md')).toBe('my personal setup notes\n')
  })
})

describe('init: onboarding (SPEC-025)', () => {
  const appify = () => {
    writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'host', devDependencies: { tailwindcss: '^4.0.0' } }))
    writeFileSync(join(root, 'tsconfig.json'), JSON.stringify({ compilerOptions: { paths: { '@/*': ['./src/*'] } } }))
    mkdirSync(join(root, 'src'), { recursive: true })
    writeFileSync(join(root, 'src', 'index.css'), '@import "tailwindcss";')
  }

  it('setup.md is the conversational flow: pitch, two STOPs, the first draft', () => {
    init(root, OPTS)
    const s = read('instructions/setup.md')
    expect(s).toContain('what are we building')
    expect((s.match(/STOP/g) ?? []).length).toBeGreaterThanOrEqual(2)
    expect(s).toContain('welcome.md')
    expect(s).toContain('#/b/')
  })

  it('a stale marver-authored setup.md is refreshed in place', () => {
    init(root, OPTS)
    const setup = join(root, 'design', 'instructions', 'setup.md')
    writeFileSync(setup, '# Setup required - old template\nrun npx marver init\n')
    init(root, OPTS)   // still no app: ours + stale -> current template
    expect(read('instructions/setup.md')).toContain('what are we building')
  })

  it('setup->app transition refreshes pristine tsconfig.json (standalone -> extends)', () => {
    init(root, OPTS)   // no root tsconfig -> standalone design/tsconfig.json
    expect(read('tsconfig.json')).not.toContain('"extends"')
    appify()
    init(root, OPTS)
    expect(existsSync(join(root, 'design', 'instructions', 'setup.md'))).toBe(false)
    expect(read('tsconfig.json')).toContain('"extends"')
    expect(read('tsconfig.json')).toContain('"@/*"')
  })

  it('setup->app transition never touches an edited tsconfig or providers', () => {
    init(root, OPTS)
    writeFileSync(join(root, 'design', 'tsconfig.json'), '{ "my": "own" }\n')
    writeFileSync(join(root, 'design', 'providers.tsx'), '// mine\n')
    appify()
    init(root, OPTS)
    expect(read('tsconfig.json')).toBe('{ "my": "own" }\n')
    expect(read('providers.tsx')).toBe('// mine\n')
  })

  it('welcome.md ships in instructions/ and AGENTS.md routes to it', () => {
    init(root, OPTS)
    expect(read('instructions/welcome.md')).toMatch(/^<!-- marver:managed [0-9a-f]{64} /)
    expect(read('AGENTS.md')).toContain('instructions/welcome.md')
  })

  it('an edited setup.md is preserved while no-app, and survives the transition', () => {
    init(root, OPTS)
    const setup = join(root, 'design', 'instructions', 'setup.md')
    writeFileSync(setup, readFileSync(setup, 'utf8') + '\nMY NOTES\n')
    init(root, OPTS)   // still no app: edited -> untouched
    expect(readFileSync(setup, 'utf8')).toContain('MY NOTES')
    appify()
    init(root, OPTS)   // app detected: edited -> kept, told to delete manually
    expect(existsSync(setup)).toBe(true)
    expect(readFileSync(setup, 'utf8')).toContain('MY NOTES')
  })
})
