import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { init } from '../src/cli/init.ts'

/** init tests run against a real temp dir - init is filesystem-in, filesystem-out. */
let root: string
beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), 'mv-init-'))
  writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'host', devDependencies: {} }))
  vi.spyOn(console, 'log').mockImplementation(() => {})
  vi.spyOn(console, 'warn').mockImplementation(() => {})
  vi.spyOn(console, 'error').mockImplementation(() => {})
})
afterEach(() => {
  rmSync(root, { recursive: true, force: true })
  vi.restoreAllMocks()
})

const OPTS = { mode: 'studio' as const, demo: false }
const read = (rel: string) => readFileSync(join(root, 'design', rel), 'utf8')

describe('init: the method layer (0.2.2)', () => {
  it('scaffolds instructions/ with markers, and setup.md in a no-app repo', () => {
    init(root, OPTS)
    for (const f of ['configure', 'discover', 'wireframe', 'brand', 'craft', 'components', 'review', 'boards'])
      expect(read(`instructions/${f}.md`)).toMatch(/^<!-- generated by marver init/)
    expect(read('instructions/setup.md')).toMatch(/^# Setup required/)
    expect(read('AGENTS.md')).toContain('design/instructions/setup.md')
    expect(read('AGENTS.md')).toContain('## The method (binding)')
  })

  it('re-init after the app appears: deletes setup.md, regenerates the contract', () => {
    init(root, OPTS)
    writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'host', devDependencies: { tailwindcss: '^4.0.0' } }))
    mkdirSync(join(root, 'src'), { recursive: true })
    writeFileSync(join(root, 'src', 'index.css'), '@import "tailwindcss";')
    init(root, OPTS)
    expect(existsSync(join(root, 'design', 'instructions', 'setup.md'))).toBe(false)
    expect(read('AGENTS.md')).not.toContain('STOP - this repo has no app yet')
    expect(read('AGENTS.md')).toContain("app's Tailwind classes")
  })

  it('managed refresh: marker-carrying files update, marker-less files are owned', () => {
    init(root, OPTS)
    const craft = join(root, 'design', 'instructions', 'craft.md')
    // owned: marker deleted + custom content survives re-init
    writeFileSync(craft, '# my own rules\n')
    init(root, OPTS)
    expect(read('instructions/craft.md')).toBe('# my own rules\n')
    // managed: stale marker-carrying content refreshes
    writeFileSync(craft, '<!-- generated by marver init (older wording) -->\nstale\n')
    init(root, OPTS)
    expect(read('instructions/craft.md')).toContain('# Craft')
  })

  it('collision guard: refuses a non-marver design/, allows a marver-shaped one', () => {
    mkdirSync(join(root, 'design'))
    writeFileSync(join(root, 'design', 'assets.txt'), 'not ours')
    const exit = vi.spyOn(process, 'exit').mockImplementation(() => { throw new Error('exit') })
    expect(() => init(root, OPTS)).toThrow('exit')
    expect(exit).toHaveBeenCalledWith(1)
    // marver-shaped by content: config.ts mentioning marver
    writeFileSync(join(root, 'design', 'config.ts'), '// marver config\nexport default {}\n')
    expect(() => init(root, OPTS)).not.toThrow()
  })

  it('a foreign setup.md is never deleted', () => {
    init(root, OPTS)   // no-app: writes our setup.md
    const setup = join(root, 'design', 'instructions', 'setup.md')
    writeFileSync(setup, 'my personal setup notes\n')
    writeFileSync(join(root, 'package.json'), JSON.stringify({ name: 'host', devDependencies: { tailwindcss: '^4.0.0' } }))
    init(root, OPTS)   // app detected - would delete OUR setup.md, must keep theirs
    expect(read('instructions/setup.md')).toBe('my personal setup notes\n')
  })
})
